### PR TITLE
Added more password pattern regexs

### PR DESCRIPTION
**Pull request by emanuelet**

### CODE REVIEW

**Comment by WellingtonCosta** [comment]
Hi @emanuelet 

I would like that the pull requests be made only in ```development``` branch.

And the patterns in the class ```convalida/src/main/java/convalida/library/util/Patterns.java``` is not mandatory to use. The developer can create your own validation patterns.

Thanks for your contributions! ;)

**Comment by emanuelet** [comment]
Ok I rebased the branch.
And yeah I know that they're not mandatory but is good to provide some built-ins

**Comment by emanuelet** [comment]
the beautifier of Atom did that. I believe it's more compatible with Github markdown which is slightly different from the normal one

**Comment by WellingtonCosta** [comment]
Hmmm. Ok.

Can I release a new version?

**Comment by emanuelet** [comment]
well, that's up to you

**Comment by WellingtonCosta** [comment]
Ok. I release a new version later.

**Pull request merged**
